### ISSUE TITLE
Doesn't work on mac

### ISSUE THREAD

**Issue by olivia-banks** [end2endzone/RapidAssist#55]
Throughout the source code, a number of preprocessor directives are given following this pattern
`
#ifdef _WIN32 
    /* bla bla bla*/ 
#elseif __linux__ 
    /* bla bla bla */ 
#endif 
`

If compilation occurs on a mac, then `_WIN32` or `__linux__ `is not defined. This should be trivial to fix, as most of the Linux code can be ported over to make pretty easily. If any of you do not have time, I would be happy to resolve this issue myself, as I am currently doing it right now to satisfy the needs of bin2cpp.

Thanks!

**Comment by end2endzone** [comment]
Hi. Thank you for the feedback. I really appreciate it.

I did not listed macOS as a [supported platform](https://github.com/end2endzone/RapidAssist#platform) because I do not own a mac and can't really test the code and functionalities. I would be really happy to add macOS support to RapidAssist. If you provide a push request with the required changes, I would gladly add them to the repository.

If I understand you correctly, the current code code under `__linux__` preprocessor should also be compilable under `__APPLE__`
preprocessor. I might be too naive but I hope that most of the current code is already mac proof. As far as I know, CMake is also [available on mac](https://stackoverflow.com/questions/30668601/installing-cmake-command-line-tools-on-a-mac), so creating the project files (or makefiles) on mac should not be an issue.

**Comment by olivia-banks** [comment]
cmake is available on mac. Mac compilers don't define __linux__, because Mac is built on XNU and Darwin. I'm currently busy, but I would be happy to do some unit testing and make your "cross platform" library run on the big 3 (windows, mac, linux).

Thanks!

**Comment by end2endzone** [comment]
I will leave the issue open even after #56 is closed.

According to [Travis user documentation](https://docs.travis-ci.com/user/reference/osx/), Travis provides an osx environment. Once the code can be compiled on osx, I will try to modify the build recipe to get Travis to build RapidAssist on osx. This will allow the code to "stay" compilable on osx with futures commits.

**Comment by end2endzone** [comment]
I managed to to get my hands on a macOS running catalina 10.15. Will try to fix things as much as I can.  I would gladly accept correction and contribution for fixing the issue. I have created branch [feature-issue55](https://github.com/end2endzone/RapidAssist/tree/feature-issue55) for the change.
