### ISSUE TITLE
Library needs administrative rights

### ISSUE THREAD

**Issue by sidey79** [end2endzone/RapidAssist#9]
When running
`cmake --build . --config Release --target INSTALL`

The library trys to install in a directory, where admin rights are needed.

```
PostBuildEvent:
  setlocal
  "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
  if %errorlevel% neq 0 goto :cmEnd
  :cmEnd
  endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
  :cmErrorLevel
  exit /b %1
  :cmDone
  if %errorlevel% neq 0 goto :VCEnd
  :VCEnd
  -- Install configuration: "Release"
  CMake Error at cmake_install.cmake:36 (file):
    file cannot create directory: C:/Program Files
    (x86)/RapidAssist/lib/rapidassist-0.4.1.  Maybe need administrative
    privileges.
```

**Comment by end2endzone** [comment]
It is not RapidAssit that does this but CMake.

If you do not specify `-DCMAKE_INSTALL_PREFIX=<somedir>` at cmake configuration time, cmake will select a default installation directory by default. See [comments in CMakeList.txt](https://github.com/end2endzone/RapidAssist/blob/master/CMakeLists.txt#L186) for reference.

By default on Windows, cmake chooses `C:\Program Files (x86)\${PROJECT_NAME}` which requires administrative privileges. That is why `install_googletest.bat` and other install scripts uses a [custom install directory](https://github.com/end2endzone/RapidAssist/blob/master/ci/appveyor/install_googletest.bat#L28).

I am supprised that you ran into this problem since it should also occurs for googletest as well.

**Comment by sidey79** [comment]
This should be added to the docs.
I've specified the install prefix to a directory which is writeable.
Because this isn't in the search path of cmake i hat to specify this also.

**Comment by end2endzone** [comment]
I am not sure I understand what you mean.
You want to add in the documentation that you must specify `-DCMAKE_INSTALL_PREFIX=<somedir>` and that <somedir> must be writable ?
Or that if you do not specify `-DCMAKE_INSTALL_PREFIX=<somedir>`, cmake will [default to a directory](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) that is not writable ?

Can you provide an examples of what you would like to see in the documentation.

**Comment by end2endzone** [comment]
Now that pull request #10 is completed, are you OK to close the issue?
